# requiring the environment of python 3.9
image: python:3.9-slim-buster

test:
  stage: test
  before_script:
    - apt update && apt -y install make
    - make install
  script:
    - make test
  only:
    - master
